### ISSUE TITLE
Create a CI dedicated goreleaser.docker.yaml

### ISSUE THREAD

**Issue by sailorlqh** [abcxyz/pmap#165]
No need to release prober images in the ci workflow.

**Comment by capri-xiyue** [comment]
@sailorlqh Could you add more context? We still need to be able to validate the prober build process for each ci/cd run.

**Comment by sailorlqh** [comment]
We decided to only release prober with `OS = linux` and `ARCH = amd64` as we don't expect prober to be run in other OS and Arch. We still kept prober release within the CI workflow, because this is an essential part of the CI/CD check.
