### ISSUE TITLE
Differentiate retryable err vs. not for handler.

### ISSUE THREAD

**Issue by sqin2019** [abcxyz/pmap#20]
For non-retryable error, we need to have them enter a different BQ table per design.

**Comment by sqin2019** [comment]
More context:
currently we [send all processor failure to failure messager](https://github.com/abcxyz/pmap/blob/main/pkg/server/event_handler.go#L244), we need to breakdown the processor errors further. [Example](https://github.com/abcxyz/lumberjack/blob/main/clients/go/pkg/auditerrors/auditerrors.go).

**Comment by sailorlqh** [comment]
some notes: 
- for processor errors, diff between retryable error and none retryable errors.
Some potential retryable error could be: asset inventory down, so when querying resources, got some error related to internet.

- Add dead letter topic subscription, when pubsub failed to deliver (exceeded max allowed number), write that into the bigquery table.
