### ISSUE TITLE
Add validation logic for github source attributes as object metadata in e2e test 

### ISSUE THREAD

**Issue by capri-xiyue** [abcxyz/pmap#56]
### TL;DR

In real case, https://github.com/abcxyz/pmap/blob/main/.github/workflows/snapshot-file-change.yml#L65-L69 here we put github source attributes as object metadata.
But in this integration test, we don't check if we have read these metadata and put them into the github source fields.
We should write fake github source attributes when we upload the test object so we cover this part of logic.

**Comment by sailorlqh** [comment]
close, as https://github.com/abcxyz/pmap/pull/100 fixed this.
